### PR TITLE
Add missing tutorial files

### PR DESCRIPTION
**Pull request by korlaxxalrok**

### CODE REVIEW

**Comment by undefx** [comment]
Thanks! We'll also probably want to update [`deploy.json`](https://github.com/cmu-delphi/www-crowdcast/blob/master/deploy.json) so that these files get to the right location.

**Comment by korlaxxalrok** [comment]
Ahhh. @undefx Were these files placed manually then?

**Comment by undefx** [comment]
That's right, they were part of the original (non-version control) site, placed manually.

**Comment by korlaxxalrok** [comment]
Gotcha!

**Comment by korlaxxalrok** [comment]
@undefx `deploy.json` is updated. Let me know if this looks like the right way to do this.

**Review by undefx — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
